#.travis.yml
#
language: node_js
node_js:
  - "12"

branches:
  only:
    - master
    - develop
    - release

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm cache clean --force

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN;

notifications:
  slack: triiibo:IeUWGXukkDueVzEo9xTzRAOZ